# Generated by Django 5.2 on 2025-04-21 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Brigada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('jefe_brigada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brigadas_lideradas', to=settings.AUTH_USER_MODEL)),
                ('miembros', models.ManyToManyField(related_name='brigadas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('coordenadas_asignadas', models.ManyToManyField(blank=True, to='gestion.coordenada')),
            ],
        ),
        migrations.AddField(
            model_name='coordenada',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.departamento'),
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.departamento')),
            ],
        ),
        migrations.AddField(
            model_name='coordenada',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.municipio'),
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('area_m2', models.FloatField(default=3500)),
                ('coordenada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.coordenada')),
            ],
        ),
        migrations.CreateModel(
            name='ConteoArbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=100)),
                ('diametro_cm', models.FloatField()),
                ('altura_m', models.FloatField()),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha_recoleccion', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.parcela')),
            ],
        ),
    ]
