# Generated by Django 5.2 on 2025-04-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brigada',
            name='coordenadas_asignadas',
        ),
        migrations.RemoveField(
            model_name='brigada',
            name='jefe_brigada',
        ),
        migrations.RemoveField(
            model_name='brigada',
            name='miembros',
        ),
        migrations.AddField(
            model_name='brigada',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brigada',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva'), ('en_misión', 'En misión')], default='activa', max_length=20),
        ),
        migrations.AlterField(
            model_name='brigada',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
