# Generated by Django 5.2 on 2025-04-22 02:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_brigada_coordenadas_asignadas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='brigada',
            name='miembros',
            field=models.ManyToManyField(blank=True, related_name='brigadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
