# Generated by Django 5.2 on 2025-05-07 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_brigada_coordenadas'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiembroBrigada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_externo', models.IntegerField()),
                ('username', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=50)),
                ('brigada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros_asignados', to='gestion.brigada')),
            ],
        ),
    ]
