# Generated by Django 5.2 on 2025-05-20 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_miembrobrigada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembrobrigada',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
