# Generated by Django 5.2 on 2025-05-27 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_miembrobrigada_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('condiciones_climaticas', models.CharField(max_length=255)),
                ('equipo_utilizado', models.TextField()),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('B', 'Borrador'), ('C', 'Completado'), ('V', 'Verificado')], default='B', max_length=1)),
                ('brigada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.brigada')),
                ('coordenada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.coordenada')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
