# Generated by Django 5.2 on 2025-05-28 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_registrocampo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrocampo',
            name='creado_por',
        ),
    ]
