# Generated by Django 5.2 on 2025-05-31 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_remove_registrocampo_creado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroBotanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie_identificada', models.CharField(max_length=100)),
                ('familia_botanica', models.CharField(max_length=100)),
                ('estado_fenologico', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('brigada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.brigada')),
                ('coordenada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.coordenada')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_terreno', models.CharField(max_length=100)),
                ('inclinacion', models.CharField(max_length=50)),
                ('presencia_agua', models.BooleanField()),
                ('estado_suelo', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('brigada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.brigada')),
                ('coordenada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.coordenada')),
            ],
        ),
    ]
